version: "3.8"

services:
  pg:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
  app:
    build: .
    command: yarn start
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/app/todo-list
